server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybtabis配置文件所在地址
  type-aliases-package: com.trust.one.entities # 所有model别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                # mapper映射文件
  
  
  
spring:
  application:  #即使是多个服务者的情况也不可修改 
    name: sonprovider-dept                     # 对外暴露的微服务名称 即注册中心显示的微服务名称 即Application的对应值
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver         # mysql驱动包
    url: jdbc:mysql://localhost:3306/cff?characterEncoding=utf8       # mysql连接数据库路径
    username: root
    password: cfymvp  
    dbcp2:
      min-idle: 5                                    # 数据库连接池的最小维持连接数
      initial-size: 5                                # 初始化连接数
      max-total: 5                                   # 最大连接数
      max-wait-millis: 200                           # 等待连接获取的最大超时时间
  